name: CD Pipeline - branche prod

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # JOB 1 - Scan sécurité
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan vulnérabilités avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  # JOB 2 - Déploiement sur runner_prod
  deploy:
    needs: scan
    runs-on: runner_prod
    steps:
      - name: Pull image depuis Docker Hub
        run: docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Arrêter l'ancien conteneur
        run: docker stop intranet-app
        continue-on-error: true

      - name: Supprimer l'ancien conteneur
        run: docker rm intranet-app
        continue-on-error: true

      - name: Lancer le nouveau conteneur
        run: |
          docker run -d -p 80:80 --name intranet-app ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}